package(default_visibility = ["//visibility:public"])

# exports_files(
#     ["runner.bash.template"],
# )

# alias(
#     name = "stately_tool",
#     actual = select({
#         "@bazel_tools//src/conditions:linux_x86_64": "@stately_linux//:stately",
#         "@bazel_tools//src/conditions:darwin": "@stately_osx//:stately",
#     }),
# )
